version: '3'

services:
  # Database
  barbeque_mysql:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: kmzway87aa
      MYSQL_DATABASE: wordpress
      MYSQL_USER: root
      MYSQL_PASSWORD: kmzway87aa
    networks:
      - barbeque
  # phpmyadmin
  barbeque_phpmyadmin:
    depends_on:
      - barbeque_mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
        - 8080:80
    environment:
      PMA_HOST: barbeque_mysql
      MYSQL_ROOT_PASSWORD: kmzway87aa 
    networks:
      - barbeque
  # Wordpress
  barbeque:
    depends_on:
      - barbeque_mysql
    image: wordpress:latest
    restart: always
    ports:
        - 8000:80
    volumes: ['./:/var/www/html']
    environment:
      WORDPRESS_DB_HOST: barbeque_mysql:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: kmzway87aa
    networks:
      - barbeque
networks:
  barbeque:
volumes:
  db_data: